### ISSUE TITLE
Fexra Web Wallet Bug Tracker

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/meta#110]

**Comment by RocksteadyTC** [comment]
- [ ] - about 50% of the time when I create a new account inside my new account, I get 502 bad gateway, and a refresh creates it anyway
- [ ] - creating an account with the name "i dont even care I just want free money at this point" gives me success and awards me TRTL but doesnt create or display an account
- [ ] - click MAX turtle when sending TRTL sets the fee and amount to -0.10
- [ ] it lets me send negative amounts
- [ ] - I just sent negative 1 million
- [ ] - when an account is deleted, don't delete the funds, make them select an account or create a new one for them to dump it into
- [ ] -  specify the change address and the address to take the balance from in walletd

**Comment by hwweddle** [comment]
When I add a value to the TRTL side of the transaction first, it doesn't always update the USD side (USD remains at 0.00). Then when I delete the TRTL value first, the USD side doesn't clear right away. This doesn't happen when I do it in the opposite direction

![screen shot 2018-06-16 at 8 13 54 pm](https://user-images.githubusercontent.com/3854023/41503426-fe11f71e-71a1-11e8-942a-d14116bc2e7b.png)

![screen shot 2018-06-16 at 8 11 39 pm](https://user-images.githubusercontent.com/3854023/41503417-b32c0bea-71a1-11e8-86a1-8d1b51506a05.png)

Mac 10.13.5
Chrome Version 67.0.3396.87 (Official Build) (64-bit)

**Comment by turtlefan** [comment]
I created two accounts and I can send an infinite amount of TRTL from one to another non stop:

![trtl](https://user-images.githubusercontent.com/40327882/41503792-0868a826-71ab-11e8-8b15-dd665375277e.png)

**Comment by turtlefan** [comment]
I created an account with a ridiculously long name and the wallet crashed. 

discord: @turtle_fan

**Comment by hwweddle** [comment]
Not sure if these displays are supposed to be this way (as I am still getting confirmations coming in), but as you can see, I created 3 new test accounts, then transferred 7672.55 TRTL from account 2 to account 1, but the percentage values on the left side of the screen aren't accurate based on the amount of TRTL I sent.
![screen shot 2018-06-16 at 9 45 31 pm](https://user-images.githubusercontent.com/3854023/41503952-db436864-71ae-11e8-92c0-f54ad57fc2df.png)

**Comment by fexra** [comment]
@hwweddle the balances on the left only show available balances, the transfers on the right show total balance including the locked amount. I willl make it more clear. Regarding the amounts and error field on the transfer modal, could you hard refresh/clear your cache and try again. I think I solved it.

@turtlefan Fix in the works, seems to be a bug in the 10,000 on account creation code that allows certain addresses to take amounts from the main address when it has insufficient balance.

**Comment by hwweddle** [comment]
Hi @fexra - Thanks for clarifying the percents---although, I'm adding some more detail because I think there is an issue beyond that. Attached are some screenshots. I made three test accounts, and each had 10000 TRTL in it---they all looked like this:
![screen shot 2018-06-17 at 8 44 37 pm](https://user-images.githubusercontent.com/3854023/41513813-8f19f2a2-726f-11e8-9f48-a293d4ef959b.png)
To test, I transferred 7672.55 TRTL from account 2 to account 1. Here's the confirmation, but note that I'm still stuck on 12/20 confirms. (suggested improvement---add the "from" account in the transaction confirmation!)
![screen shot 2018-06-17 at 8 43 34 pm](https://user-images.githubusercontent.com/3854023/41513822-b828853c-726f-11e8-9065-08e93c11c3fe.png)
Now I look at account 2 --- it shows an outgoing transaction with 12/20 confirms (but stuck on 12). There is a 0 TRTL balance, but there should still be ~2300 TRTL left. 0 TRTL balance doesn't make sense if I'm waiting for a "pending available" balance because there should be ~2300 TRTL left in the account.
![screen shot 2018-06-17 at 8 44 27 pm](https://user-images.githubusercontent.com/3854023/41513863-20fe03c0-7270-11e8-8be6-758e5dabac9b.png)
Now I look at account 1 --- it shows an incoming transaction with 12/20 confirms (but stuck on 12). There is a 600 TRTL balance, but there should be at least 10000 TRTL left. 600 TRTL balance doesn't make sense either in this situation, even if I'm waiting for a "pending available" balance because there should be at least 10000 TRTL in the account.
![screen shot 2018-06-17 at 8 43 27 pm](https://user-images.githubusercontent.com/3854023/41513899-65bbabb6-7270-11e8-84b9-a1360ce5f2a3.png)
Let me know if you need more detail or explanation!

**Comment by fexra** [comment]
@hwweddle hey yeh it's all messed up! I'm working on fixing it. Last night right before Rock posted the announcement I was fiddling with the code and now it's logging all the wrong inputs and outputs, messing up the cached balances. It comes over as a really weird bug, and is only affected some of the accounts, but a fix is in the works :)

**Comment by hwweddle** [comment]
Hello! Went in to try another xfer after a hard reset and opened in incognito window, and my accounts are all back to zero lol
![screen shot 2018-06-18 at 2 45 16 pm](https://user-images.githubusercontent.com/3854023/41555705-7f217608-7306-11e8-8d56-a674a091eea9.png)
